# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dsturnbull-carrierwave}
  s.version = "0.4.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Turnbull"]
  s.date = %q{2010-05-07}
  s.description = %q{    Fork with some nice features
}
  s.email = %q{dsturnbull@me.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Generators",
     "History.txt",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "cucumber.yml",
     "dsturnbull-carrierwave.gemspec",
     "features/caching.feature",
     "features/download.feature",
     "features/file_storage.feature",
     "features/file_storage_overridden_filename.feature",
     "features/file_storage_overridden_store_dir.feature",
     "features/file_storage_reversing_processor.feature",
     "features/fixtures/bork.txt",
     "features/fixtures/monkey.txt",
     "features/grid_fs_storage.feature",
     "features/mount_activerecord.feature",
     "features/mount_datamapper.feature",
     "features/step_definitions/activerecord_steps.rb",
     "features/step_definitions/caching_steps.rb",
     "features/step_definitions/datamapper_steps.rb",
     "features/step_definitions/download_steps.rb",
     "features/step_definitions/file_steps.rb",
     "features/step_definitions/general_steps.rb",
     "features/step_definitions/mount_steps.rb",
     "features/step_definitions/store_steps.rb",
     "features/support/activerecord.rb",
     "features/support/datamapper.rb",
     "features/support/env.rb",
     "features/versions_basics.feature",
     "features/versions_nested_versions.feature",
     "features/versions_overridden_filename.feature",
     "features/versions_overriden_store_dir.feature",
     "lib/carrierwave.rb",
     "lib/carrierwave/compatibility/paperclip.rb",
     "lib/carrierwave/core_ext/blank.rb",
     "lib/carrierwave/core_ext/inheritable_attributes.rb",
     "lib/carrierwave/core_ext/module_setup.rb",
     "lib/carrierwave/mount.rb",
     "lib/carrierwave/orm/activerecord.rb",
     "lib/carrierwave/orm/datamapper.rb",
     "lib/carrierwave/orm/mongoid.rb",
     "lib/carrierwave/orm/mongomapper.rb",
     "lib/carrierwave/orm/sequel.rb",
     "lib/carrierwave/processing/image_science.rb",
     "lib/carrierwave/processing/mini_magick.rb",
     "lib/carrierwave/processing/rmagick.rb",
     "lib/carrierwave/sanitized_file.rb",
     "lib/carrierwave/storage/abstract.rb",
     "lib/carrierwave/storage/file.rb",
     "lib/carrierwave/storage/grid_fs.rb",
     "lib/carrierwave/storage/right_s3.rb",
     "lib/carrierwave/storage/s3.rb",
     "lib/carrierwave/test/matchers.rb",
     "lib/carrierwave/uploader.rb",
     "lib/carrierwave/uploader/cache.rb",
     "lib/carrierwave/uploader/callbacks.rb",
     "lib/carrierwave/uploader/configuration.rb",
     "lib/carrierwave/uploader/default_url.rb",
     "lib/carrierwave/uploader/download.rb",
     "lib/carrierwave/uploader/extension_whitelist.rb",
     "lib/carrierwave/uploader/mountable.rb",
     "lib/carrierwave/uploader/processing.rb",
     "lib/carrierwave/uploader/proxy.rb",
     "lib/carrierwave/uploader/remove.rb",
     "lib/carrierwave/uploader/store.rb",
     "lib/carrierwave/uploader/url.rb",
     "lib/carrierwave/uploader/versions.rb",
     "merb_generators/uploader_generator.rb",
     "pkg/carrierwave-0.4.5.gem",
     "pkg/dsturnbull-carrierwave-0.4.5.gem",
     "pkg/dsturnbull-carrierwave-0.4.6.gem",
     "rails_generators/uploader/USAGE",
     "rails_generators/uploader/templates/uploader.rb",
     "rails_generators/uploader/uploader_generator.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/compatibility/paperclip_spec.rb",
     "spec/fixtures/bork.txt",
     "spec/fixtures/landscape.jpg",
     "spec/fixtures/portrait.jpg",
     "spec/fixtures/test.jpeg",
     "spec/fixtures/test.jpg",
     "spec/mount_spec.rb",
     "spec/orm/activerecord_spec.rb",
     "spec/orm/datamapper_spec.rb",
     "spec/orm/mongoid_spec.rb",
     "spec/orm/mongomapper_spec.rb",
     "spec/orm/sequel_spec.rb",
     "spec/processing/image_science_spec.rb",
     "spec/processing/mini_magick_spec.rb",
     "spec/processing/rmagick_spec.rb",
     "spec/sanitized_file_spec.rb",
     "spec/spec_helper.rb",
     "spec/storage/grid_fs_spec.rb",
     "spec/storage/right_s3_spec.rb",
     "spec/storage/s3_spec.rb",
     "spec/uploader/cache_spec.rb",
     "spec/uploader/configuration_spec.rb",
     "spec/uploader/default_url_spec.rb",
     "spec/uploader/download_spec.rb",
     "spec/uploader/extension_whitelist_spec.rb",
     "spec/uploader/mountable_spec.rb",
     "spec/uploader/paths_spec.rb",
     "spec/uploader/processing_spec.rb",
     "spec/uploader/proxy_spec.rb",
     "spec/uploader/remove_spec.rb",
     "spec/uploader/store_spec.rb",
     "spec/uploader/url_spec.rb",
     "spec/uploader/versions_spec.rb"
  ]
  s.homepage = %q{http://github.com/dsturnbull/carrierwave}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{fork of carrierwave}
  s.test_files = [
    "spec/compatibility/paperclip_spec.rb",
     "spec/mount_spec.rb",
     "spec/orm/activerecord_spec.rb",
     "spec/orm/datamapper_spec.rb",
     "spec/orm/mongoid_spec.rb",
     "spec/orm/mongomapper_spec.rb",
     "spec/orm/sequel_spec.rb",
     "spec/processing/image_science_spec.rb",
     "spec/processing/mini_magick_spec.rb",
     "spec/processing/rmagick_spec.rb",
     "spec/sanitized_file_spec.rb",
     "spec/spec_helper.rb",
     "spec/storage/grid_fs_spec.rb",
     "spec/storage/right_s3_spec.rb",
     "spec/storage/s3_spec.rb",
     "spec/uploader/cache_spec.rb",
     "spec/uploader/configuration_spec.rb",
     "spec/uploader/default_url_spec.rb",
     "spec/uploader/download_spec.rb",
     "spec/uploader/extension_whitelist_spec.rb",
     "spec/uploader/mountable_spec.rb",
     "spec/uploader/paths_spec.rb",
     "spec/uploader/processing_spec.rb",
     "spec/uploader/proxy_spec.rb",
     "spec/uploader/remove_spec.rb",
     "spec/uploader/store_spec.rb",
     "spec/uploader/url_spec.rb",
     "spec/uploader/versions_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

